Software Comparison - Correlation Plots

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

Load the annotated results

Load Salmon-map DE results

In [2]:
salmon_map_DE = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_map_dominance_DE_sex_results_new_filtering_genotype_controlled.csv", float_precision='legacy')
# Replace the zeros in padj with 1e-308 avoid log10 issues
salmon_map_DE["padj_safe"] = salmon_map_DE["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
salmon_map_DE["neglog10_padj"] = -np.log10(salmon_map_DE["padj_safe"])


# Add significance to differentially expressed transcripts 
salmon_map_DE["significant"] = (
    (salmon_map_DE["padj"] < 0.05) &
    (salmon_map_DE["log2FoldChange"].abs() > 1)
)

# Add a label to the significant transcripts
salmon_map_DE["label"] = salmon_map_DE["transcript_id"].where(salmon_map_DE["significant"], "")

salmon_map_DE

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,248.420188,0.640709,0.110526,5.796904,6.755020e-09,1.316673e-08,g2.t1,g2,utg000001l,220384.0,...,-,-,ko:K02273,"ko00190,ko01100,ko04260,ko04714,ko04932,ko0501...",I,"2FBM0@1|root,2TCUK@2759|Eukaryota,398E5@33154|...",1.316673e-08,7.880522,False,
1,92.726112,0.650988,0.104454,6.232321,4.595741e-10,9.353175e-10,g3.t1,g3,utg000001l,227675.0,...,"GO:0003674,GO:0005488,GO:0005515,GO:0005543,GO...",3.1.26.5,"ko:K14529,ko:K17543","ko03013,map03013",DUZ,"KOG2101@1|root,KOG2101@2759|Eukaryota,396Y9@33...",9.353175e-10,9.029041,False,
2,136.044931,-0.600974,0.070022,-8.582668,9.269779e-18,2.387530e-17,g4.t1,g4,utg000001l,245866.0,...,"GO:0001101,GO:0001666,GO:0003674,GO:0003824,GO...",2.5.1.61,ko:K01749,"ko00860,ko01100,ko01110,ko01120,map00860,map01...",H,"COG0181@1|root,KOG2892@2759|Eukaryota,38D6W@33...",2.387530e-17,16.622051,False,
3,3.332468,2.699629,0.718636,3.756600,1.722376e-04,2.671748e-04,g5.t1,g5,utg000001l,257697.0,...,"GO:0005575,GO:0005622,GO:0005623,GO:0005737,GO...",-,-,-,I,"KOG2761@1|root,KOG2761@2759|Eukaryota,38F7R@33...",2.671748e-04,3.573204,True,g5.t1
4,381.084979,-0.875080,0.046175,-18.951587,4.284679e-80,3.659726e-79,g6.t1,g6,utg000001l,263441.0,...,-,-,-,-,B,"2E6V3@1|root,2SDHR@2759|Eukaryota",3.659726e-79,78.436551,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17569,20.275098,0.319252,0.150056,2.127555,3.337403e-02,4.238130e-02,g34843.t1,g34843,utg003648l,5656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.238130e-02,1.372826,False,
17570,1.364118,2.068769,0.590743,3.501981,4.618132e-04,6.956768e-04,g34884.t1,g34884,utg003700l,19710.0,...,-,-,-,-,S,"2D3G7@1|root,2SRFN@2759|Eukaryota,3AMW9@33154|...",6.956768e-04,3.157592,True,g34884.t1
17571,8.286716,1.984267,0.355927,5.574921,2.476423e-08,4.718367e-08,g34922.t1,g34922,utg003714l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.718367e-08,7.326208,True,g34922.t1
17572,19.121063,2.284212,0.326813,6.989347,2.761695e-12,6.049015e-12,g35167.t1,g35167,utg003885l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,6.049015e-12,11.218315,True,g35167.t1
17573,3.504696,1.065212,0.357173,2.982341,2.860533e-03,4.036436e-03,g35420.t1,g35420,utg003980l,11626.0,...,-,2.4.2.29,ko:K15407,-,C,"KOG1075@1|root,KOG1075@2759|Eukaryota,39TZY@33...",4.036436e-03,2.394002,True,g35420.t1

Load STAR+featureCounts DE results

In [3]:
star_DE = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/STAR_featureCounts_deseq2_sex_results_fully_annotated_new_filtering_genotype_controlled.csv", float_precision='legacy')
# Replace the zeros in padj with 1e-308 avoid log10 issues
star_DE["padj_safe"] = star_DE["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
star_DE["neglog10_padj"] = -np.log10(star_DE["padj_safe"])


# Add significance to differentially expressed transcripts 
star_DE["significant"] = (
    (star_DE["padj"] < 0.05) &
    (star_DE["log2FoldChange"].abs() > 1)
)

# Add a label to the significant transcripts
star_DE["label"] = star_DE["transcript_id"].where(star_DE["significant"], "")

star_DE

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,1.153465,-1.195420,0.551975,-2.165713,3.033315e-02,3.822530e-02,g1.t1,g1,utg000001l,185292,...,"GO:0005575,GO:0005622,GO:0005623,GO:0005634,GO...",-,-,-,-,"2DQGE@1|root,2S6BS@2759|Eukaryota,3A6U0@33154|...",3.822530e-02,1.417649,True,g1.t1
1,456.100314,0.549442,0.094234,5.830616,5.522321e-09,1.081591e-08,g10.t1,g10,utg000001l,554496,...,"GO:0003674,GO:0005488,GO:0005509,GO:0043167,GO...",-,-,-,T,"KOG0032@1|root,KOG0032@2759|Eukaryota,38G5X@33...",1.081591e-08,7.965937,False,
2,1836.622862,0.657428,0.060016,10.954129,6.348627e-28,2.155069e-27,g1000.t1,g1000,utg000005l,5092168,...,"GO:0003674,GO:0003824,GO:0004518,GO:0004540,GO...",3.1.27.1,ko:K01166,-,A,"KOG1642@1|root,KOG1642@2759|Eukaryota,38KSQ@33...",2.155069e-27,26.666539,False,
3,9.277403,1.289546,0.202372,6.372162,1.863813e-10,3.850315e-10,g10001.t1,g10001,utg000074l,8915422,...,-,-,-,-,B,"KOG4585@1|root,KOG4585@2759|Eukaryota",3.850315e-10,9.414504,True,g10001.t1
4,5.817209,-0.414017,0.359092,-1.152955,2.489288e-01,2.781148e-01,g10006.t1,g10006,utg000074l,9020033,...,NaN,NaN,NaN,NaN,NaN,NaN,2.781148e-01,0.555776,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17561,20.318618,0.343267,0.136656,2.511913,1.200786e-02,1.580774e-02,g999.t1,g999,utg000005l,4837205,...,"GO:0003674,GO:0003824,GO:0005575,GO:0005622,GO...",-,ko:K17888,"ko04136,ko04138,ko04140,map04136,map04138,map0...",S,"KOG4741@1|root,KOG4741@2759|Eukaryota,39WIU@33...",1.580774e-02,1.801130,False,
17562,5.285936,0.955963,0.233390,4.095991,4.203661e-05,6.760619e-05,g9991.t1,g9991,utg000074l,8820390,...,-,-,-,-,L,"KOG4585@1|root,KOG4585@2759|Eukaryota,3A4U2@33...",6.760619e-05,4.170014,False,
17563,3.573162,1.351802,0.257945,5.240660,1.600034e-07,2.938895e-07,g9992.t1,g9992,utg000074l,8822623,...,NaN,NaN,NaN,NaN,NaN,NaN,2.938895e-07,6.531816,True,g9992.t1
17564,9.375622,0.486381,0.343096,1.417625,1.563002e-01,1.800897e-01,g9993.t1,g9993,utg000074l,8847120,...,-,-,-,-,K,"2E8EB@1|root,2SEWX@2759|Eukaryota,3AC3W@33154|...",1.800897e-01,0.744511,False,
17565,1.915054,1.185778,0.397443,2.983518,2.849555e-03,3.990879e-03,g9997.t1,g9997,utg000074l,8855626,...,-,-,-,-,-,"2BXPG@1|root,2S2FM@2759|Eukaryota,3A3WK@33154|...",3.990879e-03,2.398931,True,g9997.t1

Load Salmon-Align results

In [4]:
salmon_align_DE = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_align_dominance_DE_sex_results_new_filtering_genotype_controlled.csv", float_precision='legacy')
# Replace the zeros in padj with 1e-308 avoid log10 issues
salmon_align_DE["padj_safe"] = salmon_align_DE["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
salmon_align_DE["neglog10_padj"] = -np.log10(salmon_align_DE["padj_safe"])


# Add significance label to differentially expressed transcripts 
salmon_align_DE["significant"] = (
    (salmon_align_DE["padj"] < 0.05) &
    (salmon_align_DE["log2FoldChange"].abs() > 1)
)

# Add a label to the significant transcripts
salmon_align_DE["label"] = salmon_align_DE["transcript_id"].where(salmon_align_DE["significant"], "")

salmon_align_DE

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,237.825076,0.769809,0.108163,7.117088,1.102309e-12,2.503789e-12,g2.t1,g2,utg000001l,220384.0,...,-,-,ko:K02273,"ko00190,ko01100,ko04260,ko04714,ko04932,ko0501...",I,"2FBM0@1|root,2TCUK@2759|Eukaryota,398E5@33154|...",2.503789e-12,11.601402,False,
1,73.844964,0.632045,0.112596,5.613409,1.983792e-08,3.880485e-08,g3.t1,g3,utg000001l,227675.0,...,"GO:0003674,GO:0005488,GO:0005515,GO:0005543,GO...",3.1.26.5,"ko:K14529,ko:K17543","ko03013,map03013",DUZ,"KOG2101@1|root,KOG2101@2759|Eukaryota,396Y9@33...",3.880485e-08,7.411114,False,
2,115.316375,-0.606464,0.077147,-7.861169,3.805645e-15,9.357857e-15,g4.t1,g4,utg000001l,245866.0,...,"GO:0001101,GO:0001666,GO:0003674,GO:0003824,GO...",2.5.1.61,ko:K01749,"ko00860,ko01100,ko01110,ko01120,map00860,map01...",H,"COG0181@1|root,KOG2892@2759|Eukaryota,38D6W@33...",9.357857e-15,14.028824,False,
3,251.432475,-0.863871,0.048939,-17.652036,9.815309e-70,7.588271e-69,g6.t1,g6,utg000001l,263441.0,...,-,-,-,-,B,"2E6V3@1|root,2SDHR@2759|Eukaryota",7.588271e-69,68.119857,False,
4,42.078202,-0.952676,0.102605,-9.284858,1.619236e-20,4.636125e-20,g7.t1,g7,utg000001l,371755.0,...,"GO:0002682,GO:0002683,GO:0002685,GO:0002686,GO...",-,-,-,Z,"COG4886@1|root,KOG0532@2759|Eukaryota,38HCP@33...",4.636125e-20,19.333845,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16558,11.656909,0.258990,0.195667,1.323623,1.856282e-01,2.200882e-01,g34843.t1,g34843,utg003648l,5656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.200882e-01,0.657403,False,
16559,1.364347,2.030314,0.580010,3.500479,4.644220e-04,7.233045e-04,g34884.t1,g34884,utg003700l,19710.0,...,-,-,-,-,S,"2D3G7@1|root,2SRFN@2759|Eukaryota,3AMW9@33154|...",7.233045e-04,3.140679,True,g34884.t1
16560,2.364626,0.345714,0.335347,1.030913,3.025814e-01,3.453507e-01,g34922.t1,g34922,utg003714l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.453507e-01,0.461740,False,
16561,3.988477,1.095925,0.307969,3.558560,3.728934e-04,5.847220e-04,g35167.t1,g35167,utg003885l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.847220e-04,3.233051,True,g35167.t1
16562,3.287078,0.803360,0.362456,2.216434,2.666176e-02,3.548247e-02,g35420.t1,g35420,utg003980l,11626.0,...,-,2.4.2.29,ko:K15407,-,C,"KOG1075@1|root,KOG1075@2759|Eukaryota,39TZY@33...",3.548247e-02,1.449986,False,

Correlation plots.  
Pairwise comparison of BaseMean per transcript between the softwares
(=mean normalized expression estimates produced by DESeq2)

In [5]:
from scipy.stats import pearsonr, spearmanr
#funtion to extract pearson and spearman R

def report_correlation(x, y, label):
    pearson_r, _ = pearsonr(x, y)
    spearman_r, _ = spearmanr(x, y)
    print(label)
    print(f"  Pearson r  = {pearson_r:.3f}")
    print(f"  Spearman ρ = {spearman_r:.3f}\n")

In [6]:
# function to extract basemean 
def extract_basemean(df, id_col, label):
    bm = df[[id_col, "baseMean"]].copy()
    bm = bm.rename(columns={"baseMean": f"baseMean_{label}"})
    return bm

In [7]:
#extract basemean from all three 
star_bm = extract_basemean(star_DE, "transcript_id", "STAR")
salmon_map_bm = extract_basemean(salmon_map_DE, "transcript_id", "Salmon_map")
salmon_align_bm = extract_basemean(salmon_align_DE, "transcript_id", "Salmon_align")

# merge on transcript_id
merged_bm = (
    star_bm
    .merge(salmon_map_bm, on="transcript_id", how="inner")
    .merge(salmon_align_bm, on="transcript_id", how="inner")
)

print("Number of shared transcripts:", merged_bm.shape[0])
merged_bm.head()

Number of shared transcripts: 14840

  transcript_id  baseMean_STAR  baseMean_Salmon_map  baseMean_Salmon_align
0        g10.t1     456.100314           345.994755             290.822706
1      g1000.t1    1836.622862           734.336268             341.651854
2     g10006.t1       5.817209             2.487832               2.341586
3      g1001.t1      26.227040           180.730637              73.413402
4      g1002.t1     622.382157           611.077939             425.515579

In [8]:
#log10 transformation to handel RNA data

for col in ["baseMean_STAR", "baseMean_Salmon_map", "baseMean_Salmon_align"]:
    merged_bm[f"log10_{col}"] = np.log10(merged_bm[col] + 1)

merged_bm

,transcript_id,baseMean_STAR,baseMean_Salmon_map,baseMean_Salmon_align,log10_baseMean_STAR,log10_baseMean_Salmon_map,log10_baseMean_Salmon_align
0,g10.t1,456.100314,345.994755,290.822706,2.660012,2.540323,2.465119
1,g1000.t1,1836.622862,734.336268,341.651854,3.264256,2.866486,2.534853
2,g10006.t1,5.817209,2.487832,2.341586,0.833607,0.542556,0.523953
3,g1001.t1,26.227040,180.730637,73.413402,1.435000,2.259428,1.871651
4,g1002.t1,622.382157,611.077939,425.515579,2.794754,2.786807,2.629935
...,...,...,...,...,...,...,...
14835,g9973.t1,3.960454,10.464083,9.712877,0.695521,1.059339,1.029906
14836,g998.t1,65.202446,23.874433,22.435232,1.820874,1.395753,1.369869
14837,g999.t1,20.318618,28.892253,13.387113,1.328759,1.475559,1.157974
14838,g9993.t1,9.375622,6.102360,6.674590,1.016014,0.851403,0.885055
14839,g9997.t1,1.915054,22.459425,1.856460,0.464647,1.370317,0.455828

STAR + featureCounts vs Salmon_map

In [9]:
x = merged_bm["log10_baseMean_STAR"]
y = merged_bm["log10_baseMean_Salmon_map"]

pearson_r, _ = pearsonr(x, y)
spearman_r, _ = spearmanr(x, y)
r2 = pearson_r ** 2

fig = px.scatter(
    merged_bm,
    x="log10_baseMean_STAR",
    y="log10_baseMean_Salmon_map",
    opacity=0.4,
    trendline="ols",
    hover_name="transcript_id",
    labels={
        "log10_baseMean_STAR": "STAR - log10(BaseMean + 1)",
        "log10_baseMean_Salmon_map": "Salmon (map) - log10(BaseMean + 1)"
    },
    title="Overall expression agreement: STAR vs. Salmon (map)",
)

fig.add_annotation(
    x=0.05,
    y=0.95,
    xref="paper",
    yref="paper",
    showarrow=False,
    align="left",
    text=(
        f"Pearson r = {pearson_r:.3f}<br>"
        f"Spearman ρ = {spearman_r:.3f}<br>"
        f"R² = {r2:.3f}"
    )
)


fig.update_traces(
    line=dict(color="red", width=1),
    selector=dict(mode="lines")
)

fig.show()

print("STAR vs Salmon (map)")
print(f"  Pearson r  = {pearson_r:.3f}")
print(f"  Spearman ρ = {spearman_r:.3f}")
print(f"  R²         = {r2:.3f}\n")

STAR vs Salmon (map)
  Pearson r  = 0.927
  Spearman ρ = 0.927
  R²         = 0.859

STAR + featureCounts vs. STAR + Salmon_align

In [10]:
x = merged_bm["log10_baseMean_STAR"]
y = merged_bm["log10_baseMean_Salmon_align"]

pearson_r, _ = pearsonr(x, y)
spearman_r, _ = spearmanr(x, y)
r2 = pearson_r ** 2

fig = px.scatter(
    merged_bm,
    x="log10_baseMean_STAR",
    y="log10_baseMean_Salmon_align",
    opacity=0.4,
    trendline="ols",
    hover_name="transcript_id",
    labels={
        "log10_baseMean_STAR": "STAR - log10(BaseMean + 1)",
        "log10_baseMean_Salmon_align": "Salmon (align) - log10(BaseMean + 1)"
    },
    title="Overall expression agreement: STAR vs. Salmon (align)"
)

fig.add_annotation(
    x=0.05,
    y=0.95,
    xref="paper",
    yref="paper",
    showarrow=False,
    align="left",
    text=(
        f"Pearson r = {pearson_r:.3f}<br>"
        f"Spearman ρ = {spearman_r:.3f}<br>"
        f"R² = {r2:.3f}"
    )
)

fig.update_traces(
    line=dict(color="red", width=1),
    selector=dict(mode="lines")
)

fig.show()

print("STAR vs Salmon (align)")
print(f"  Pearson r  = {pearson_r:.3f}")
print(f"  Spearman ρ = {spearman_r:.3f}")
print(f"  R²         = {r2:.3f}\n")

STAR vs Salmon (align)
  Pearson r  = 0.923
  Spearman ρ = 0.924
  R²         = 0.851

Salmon map vs. STAR + Salmon align

In [11]:
x = merged_bm["log10_baseMean_Salmon_map"]
y = merged_bm["log10_baseMean_Salmon_align"]

pearson_r, _ = pearsonr(x, y)
spearman_r, _ = spearmanr(x, y)
r2 = pearson_r ** 2

fig = px.scatter(
    merged_bm,
    x="log10_baseMean_Salmon_map",
    y="log10_baseMean_Salmon_align",
    opacity=0.4,
    trendline="ols",
    hover_name="transcript_id",
    labels={
        "log10_baseMean_Salmon_map": "Salmon (map) - log10(BaseMean + 1)",
        "log10_baseMean_Salmon_align": "Salmon (align) - log10(BaseMean + 1)"
    },
    title="Overall expression agreement: Salmon map vs. Salmon align"
)

fig.add_annotation(
    x=0.05,
    y=0.95,
    xref="paper",
    yref="paper",
    showarrow=False,
    align="left",
    text=(
        f"Pearson r = {pearson_r:.3f}<br>"
        f"Spearman ρ = {spearman_r:.3f}<br>"
        f"R² = {r2:.3f}"
    )
)

fig.update_traces(
    line=dict(color="red", width=1),
    selector=dict(mode="lines")
)

fig.show()

print("Salmon map vs Salmon align")
print(f"  Pearson r  = {pearson_r:.3f}")
print(f"  Spearman ρ = {spearman_r:.3f}")
print(f"  R²         = {r2:.3f}\n")

Salmon map vs Salmon align
  Pearson r  = 0.987
  Spearman ρ = 0.987
  R²         = 0.974