Software Comparison - Correlation Plots

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

Load the annotated results

Load Salmon-map DE results

In [2]:
salmon_map_DE = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_map_dominance_DE_sex_results.csv", float_precision='legacy')
# Replace the zeros in padj with 1e-308 avoid log10 issues
salmon_map_DE["padj_safe"] = salmon_map_DE["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
salmon_map_DE["neglog10_padj"] = -np.log10(salmon_map_DE["padj_safe"])


# Add significance to differentially expressed transcripts 
salmon_map_DE["significant"] = (
    (salmon_map_DE["padj"] < 0.05) &
    (salmon_map_DE["log2FoldChange"].abs() > 1)
)

# Add a label to the significant transcripts
salmon_map_DE["label"] = salmon_map_DE["transcript_id"].where(salmon_map_DE["significant"], "")

salmon_map_DE

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,248.420188,0.692248,0.131010,5.283945,1.264310e-07,2.436236e-07,g2.t1,g2,utg000001l,220384.0,...,-,-,ko:K02273,"ko00190,ko01100,ko04260,ko04714,ko04932,ko0501...",I,"2FBM0@1|root,2TCUK@2759|Eukaryota,398E5@33154|...",2.436236e-07,6.613281,False,
1,92.726112,0.655816,0.169767,3.863035,1.119872e-04,1.816552e-04,g3.t1,g3,utg000001l,227675.0,...,"GO:0003674,GO:0005488,GO:0005515,GO:0005543,GO...",3.1.26.5,"ko:K14529,ko:K17543","ko03013,map03013",DUZ,"KOG2101@1|root,KOG2101@2759|Eukaryota,396Y9@33...",1.816552e-04,3.740752,False,
2,136.044931,-0.620457,0.178648,-3.473064,5.145527e-04,7.936587e-04,g4.t1,g4,utg000001l,245866.0,...,"GO:0001101,GO:0001666,GO:0003674,GO:0003824,GO...",2.5.1.61,ko:K01749,"ko00860,ko01100,ko01110,ko01120,map00860,map01...",H,"COG0181@1|root,KOG2892@2759|Eukaryota,38D6W@33...",7.936587e-04,3.100366,False,
3,381.084979,-0.916813,0.069608,-13.171077,1.287480e-39,7.390355e-39,g6.t1,g6,utg000001l,263441.0,...,-,-,-,-,B,"2E6V3@1|root,2SDHR@2759|Eukaryota",7.390355e-39,38.131335,False,
4,70.718212,-1.042894,0.092940,-11.221090,3.212849e-29,1.373292e-28,g7.t1,g7,utg000001l,371755.0,...,"GO:0002682,GO:0002683,GO:0002685,GO:0002686,GO...",-,-,-,Z,"COG4886@1|root,KOG0532@2759|Eukaryota,38HCP@33...",1.373292e-28,27.862237,True,g7.t1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14159,10.439363,0.155829,1.106835,0.140788,8.880376e-01,8.997925e-01,g34647.t1,g34647,utg003542l,22333.0,...,-,-,-,-,T,"COG4886@1|root,KOG4641@2759|Eukaryota,39T87@33...",8.997925e-01,0.045858,False,
14160,10.044300,0.631293,0.230505,2.738741,6.167502e-03,8.691213e-03,g34695.t1,g34695,utg003603l,1.0,...,"GO:0000003,GO:0000578,GO:0000932,GO:0001709,GO...",-,ko:K17597,-,KU,"KOG3732@1|root,KOG3732@2759|Eukaryota,38HNW@33...",8.691213e-03,2.060920,False,
14161,20.275098,0.380299,0.210397,1.807533,7.067915e-02,8.783567e-02,g34843.t1,g34843,utg003648l,5656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,8.783567e-02,1.056329,False,
14162,8.286716,2.238606,0.365799,6.119773,9.370857e-10,2.009399e-09,g34922.t1,g34922,utg003714l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.009399e-09,8.696934,True,g34922.t1
14163,19.121063,2.377056,0.338256,7.027380,2.104477e-12,5.052814e-12,g35167.t1,g35167,utg003885l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.052814e-12,11.296467,True,g35167.t1

Load STAR+featureCounts DE results

In [3]:
star_DE = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/STAR_featureCounts_deseq2_sex_results_fully_annotated.csv", float_precision='legacy')
# Replace the zeros in padj with 1e-308 avoid log10 issues
star_DE["padj_safe"] = star_DE["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
star_DE["neglog10_padj"] = -np.log10(star_DE["padj_safe"])


# Add significance to differentially expressed transcripts 
star_DE["significant"] = (
    (star_DE["padj"] < 0.05) &
    (star_DE["log2FoldChange"].abs() > 1)
)

# Add a label to the significant transcripts
star_DE["label"] = star_DE["transcript_id"].where(star_DE["significant"], "")

star_DE

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,456.100314,0.539079,0.130288,4.137586,3.509789e-05,5.845346e-05,g10.t1,g10,utg000001l,554496,...,"GO:0003674,GO:0005488,GO:0005509,GO:0043167,GO...",-,-,-,T,"KOG0032@1|root,KOG0032@2759|Eukaryota,38G5X@33...",5.845346e-05,4.233190,False,
1,1836.622862,0.664999,0.075707,8.783856,1.579635e-18,4.848653e-18,g1000.t1,g1000,utg000005l,5092168,...,"GO:0003674,GO:0003824,GO:0004518,GO:0004540,GO...",3.1.27.1,ko:K01166,-,A,"KOG1642@1|root,KOG1642@2759|Eukaryota,38KSQ@33...",4.848653e-18,17.314379,False,
2,9.277403,1.333546,0.216804,6.150915,7.703709e-10,1.663951e-09,g10001.t1,g10001,utg000074l,8915422,...,-,-,-,-,B,"KOG4585@1|root,KOG4585@2759|Eukaryota",1.663951e-09,8.778860,True,g10001.t1
3,5.817209,-0.848525,0.467592,-1.814669,6.957478e-02,8.494466e-02,g10006.t1,g10006,utg000074l,9020033,...,NaN,NaN,NaN,NaN,NaN,NaN,8.494466e-02,1.070864,False,
4,8.725202,0.915383,0.433734,2.110473,3.481764e-02,4.416126e-02,g10007.t1,g10007,utg000074l,9029095,...,-,-,-,-,S,"2EV8V@1|root,2SX9Q@2759|Eukaryota,3ASV5@33154|...",4.416126e-02,1.354959,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14486,3.644762,1.053781,0.354595,2.971785,2.960737e-03,4.238691e-03,g9975.t1,g9975,utg000074l,8597833,...,NaN,NaN,NaN,NaN,NaN,NaN,4.238691e-03,2.372768,True,g9975.t1
14487,65.202446,1.386473,0.283779,4.885748,1.030367e-06,1.889289e-06,g998.t1,g998,utg000005l,4824834,...,-,-,-,-,S,"KOG1075@1|root,KOG1075@2759|Eukaryota,3A0JU@33...",1.889289e-06,5.723702,True,g998.t1
14488,20.318618,0.332156,0.150204,2.211374,2.700997e-02,3.473258e-02,g999.t1,g999,utg000005l,4837205,...,"GO:0003674,GO:0003824,GO:0005575,GO:0005622,GO...",-,ko:K17888,"ko04136,ko04138,ko04140,map04136,map04138,map0...",S,"KOG4741@1|root,KOG4741@2759|Eukaryota,39WIU@33...",3.473258e-02,1.459263,False,
14489,5.285936,0.873696,0.343095,2.546516,1.088043e-02,1.463958e-02,g9991.t1,g9991,utg000074l,8820390,...,-,-,-,-,L,"KOG4585@1|root,KOG4585@2759|Eukaryota,3A4U2@33...",1.463958e-02,1.834471,False,
14490,9.375622,0.551407,0.503868,1.094349,2.738021e-01,3.069286e-01,g9993.t1,g9993,utg000074l,8847120,...,-,-,-,-,K,"2E8EB@1|root,2SEWX@2759|Eukaryota,3AC3W@33154|...",3.069286e-01,0.512963,False,

Load Salmon-Align results

In [4]:
salmon_align_DE = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_align_dominance_DE_sex_results.csv", float_precision='legacy')
# Replace the zeros in padj with 1e-308 avoid log10 issues
salmon_align_DE["padj_safe"] = salmon_align_DE["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
salmon_align_DE["neglog10_padj"] = -np.log10(salmon_align_DE["padj_safe"])


# Add significance label to differentially expressed transcripts 
salmon_align_DE["significant"] = (
    (salmon_align_DE["padj"] < 0.05) &
    (salmon_align_DE["log2FoldChange"].abs() > 1)
)

# Add a label to the significant transcripts
salmon_align_DE["label"] = salmon_align_DE["transcript_id"].where(salmon_align_DE["significant"], "")

salmon_align_DE

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,237.825076,0.820720,0.128718,6.376102,1.816516e-10,4.176360e-10,g2.t1,g2,utg000001l,220384.0,...,-,-,ko:K02273,"ko00190,ko01100,ko04260,ko04714,ko04932,ko0501...",I,"2FBM0@1|root,2TCUK@2759|Eukaryota,398E5@33154|...",4.176360e-10,9.379202,False,
1,73.844964,0.663088,0.181503,3.653307,2.588841e-04,4.227300e-04,g3.t1,g3,utg000001l,227675.0,...,"GO:0003674,GO:0005488,GO:0005515,GO:0005543,GO...",3.1.26.5,"ko:K14529,ko:K17543","ko03013,map03013",DUZ,"KOG2101@1|root,KOG2101@2759|Eukaryota,396Y9@33...",4.227300e-04,3.373937,False,
2,115.316375,-0.604007,0.168995,-3.574101,3.514339e-04,5.684973e-04,g4.t1,g4,utg000001l,245866.0,...,"GO:0001101,GO:0001666,GO:0003674,GO:0003824,GO...",2.5.1.61,ko:K01749,"ko00860,ko01100,ko01110,ko01120,map00860,map01...",H,"COG0181@1|root,KOG2892@2759|Eukaryota,38D6W@33...",5.684973e-04,3.245272,False,
3,251.432475,-0.890111,0.062318,-14.283463,2.774631e-46,2.061507e-45,g6.t1,g6,utg000001l,263441.0,...,-,-,-,-,B,"2E6V3@1|root,2SDHR@2759|Eukaryota",2.061507e-45,44.685815,False,
4,42.078202,-0.956786,0.113113,-8.458699,2.703768e-17,8.292135e-17,g7.t1,g7,utg000001l,371755.0,...,"GO:0002682,GO:0002683,GO:0002685,GO:0002686,GO...",-,-,-,Z,"COG4886@1|root,KOG0532@2759|Eukaryota,38HCP@33...",8.292135e-17,16.081334,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13342,43.727684,-1.073768,0.377653,-2.843267,4.465371e-03,6.588446e-03,g34609.t1,g34609,utg003498l,40065.0,...,"GO:0001654,GO:0001754,GO:0001838,GO:0001841,GO...",-,ko:K04638,"ko05016,map05016",T,"KOG0972@1|root,KOG0972@2759|Eukaryota,38NJ2@33...",6.588446e-03,2.181217,True,g34609.t1
13343,270.336130,-0.778204,0.228289,-3.408849,6.523767e-04,1.035361e-03,g34610.t1,g34610,utg003498l,51899.0,...,"GO:0000313,GO:0000315,GO:0003674,GO:0003735,GO...",-,ko:K02890,"ko03010,map03010",J,"COG0091@1|root,KOG1711@2759|Eukaryota,39N6Y@33...",1.035361e-03,2.984908,False,
13344,9.744905,-0.053340,1.043776,-0.051103,9.592435e-01,9.663404e-01,g34647.t1,g34647,utg003542l,22333.0,...,-,-,-,-,T,"COG4886@1|root,KOG4641@2759|Eukaryota,39T87@33...",9.663404e-01,0.014870,False,
13345,11.656909,0.290402,0.220917,1.314527,1.886688e-01,2.252883e-01,g34843.t1,g34843,utg003648l,5656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.252883e-01,0.647261,False,
13346,3.988477,1.152841,0.361533,3.188757,1.428861e-03,2.208075e-03,g35167.t1,g35167,utg003885l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.208075e-03,2.655986,True,g35167.t1

Correlation plots.  
Pairwise comparison of BaseMean per transcript between the softwares
(=mean normalized expression estimates produced by DESeq2)

In [5]:
from scipy.stats import pearsonr, spearmanr
#funtion to extract pearson and spearman R

def report_correlation(x, y, label):
    pearson_r, _ = pearsonr(x, y)
    spearman_r, _ = spearmanr(x, y)
    print(label)
    print(f"  Pearson r  = {pearson_r:.3f}")
    print(f"  Spearman ρ = {spearman_r:.3f}\n")

In [6]:
# function to extract basemean 
def extract_basemean(df, id_col, label):
    bm = df[[id_col, "baseMean"]].copy()
    bm = bm.rename(columns={"baseMean": f"baseMean_{label}"})
    return bm

In [7]:
#extract basemean from all three 
star_bm = extract_basemean(star_DE, "transcript_id", "STAR")
salmon_map_bm = extract_basemean(salmon_map_DE, "transcript_id", "Salmon_map")
salmon_align_bm = extract_basemean(salmon_align_DE, "transcript_id", "Salmon_align")

# merge on transcript_id
merged_bm = (
    star_bm
    .merge(salmon_map_bm, on="transcript_id", how="inner")
    .merge(salmon_align_bm, on="transcript_id", how="inner")
)

print("Number of shared transcripts:", merged_bm.shape[0])
merged_bm.head()

Number of shared transcripts: 12068

  transcript_id  baseMean_STAR  baseMean_Salmon_map  baseMean_Salmon_align
0        g10.t1     456.100314           345.994755             290.822706
1      g1000.t1    1836.622862           734.336268             341.651854
2      g1001.t1      26.227040           180.730637              73.413402
3      g1002.t1     622.382157           611.077939             425.515579
4      g1003.t1     503.721255           208.235913             166.090002

In [8]:
#log10 transformation to handel RNA data

for col in ["baseMean_STAR", "baseMean_Salmon_map", "baseMean_Salmon_align"]:
    merged_bm[f"log10_{col}"] = np.log10(merged_bm[col] + 1)

merged_bm

,transcript_id,baseMean_STAR,baseMean_Salmon_map,baseMean_Salmon_align,log10_baseMean_STAR,log10_baseMean_Salmon_map,log10_baseMean_Salmon_align
0,g10.t1,456.100314,345.994755,290.822706,2.660012,2.540323,2.465119
1,g1000.t1,1836.622862,734.336268,341.651854,3.264256,2.866486,2.534853
2,g1001.t1,26.227040,180.730637,73.413402,1.435000,2.259428,1.871651
3,g1002.t1,622.382157,611.077939,425.515579,2.794754,2.786807,2.629935
4,g1003.t1,503.721255,208.235913,166.090002,2.703052,2.320636,2.222950
...,...,...,...,...,...,...,...
12063,g996.t1,56.539735,16.869494,5.312053,1.759968,1.252112,0.800171
12064,g9973.t1,3.960454,10.464083,9.712877,0.695521,1.059339,1.029906
12065,g998.t1,65.202446,23.874433,22.435232,1.820874,1.395753,1.369869
12066,g999.t1,20.318618,28.892253,13.387113,1.328759,1.475559,1.157974
12067,g9993.t1,9.375622,6.102360,6.674590,1.016014,0.851403,0.885055

STAR + featureCounts vs Salmon_map

In [30]:
x = merged_bm["log10_baseMean_STAR"]
y = merged_bm["log10_baseMean_Salmon_map"]

pearson_r, _ = pearsonr(x, y)
spearman_r, _ = spearmanr(x, y)
r2 = pearson_r ** 2

fig = px.scatter(
    merged_bm,
    x="log10_baseMean_STAR",
    y="log10_baseMean_Salmon_map",
    opacity=0.4,
    trendline="ols",
    hover_name="transcript_id",
    labels={
        "log10_baseMean_STAR": "STAR - log10(BaseMean + 1)",
        "log10_baseMean_Salmon_map": "Salmon (map) - log10(BaseMean + 1)"
    },
    title="Overall expression agreement: STAR vs. Salmon (map)",
)

fig.add_annotation(
    x=0.05,
    y=0.95,
    xref="paper",
    yref="paper",
    showarrow=False,
    align="left",
    text=(
        f"Pearson r = {pearson_r:.3f}<br>"
        f"Spearman ρ = {spearman_r:.3f}<br>"
        f"R² = {r2:.3f}"
    )
)


fig.update_traces(
    line=dict(color="red", width=1),
    selector=dict(mode="lines")
)

fig.show()

print("STAR vs Salmon (map)")
print(f"  Pearson r  = {pearson_r:.3f}")
print(f"  Spearman ρ = {spearman_r:.3f}")
print(f"  R²         = {r2:.3f}\n")

STAR vs Salmon (map)
  Pearson r  = 0.918
  Spearman ρ = 0.915
  R²         = 0.843

STAR + featureCounts vs. STAR + Salmon_align

In [31]:
x = merged_bm["log10_baseMean_STAR"]
y = merged_bm["log10_baseMean_Salmon_align"]

pearson_r, _ = pearsonr(x, y)
spearman_r, _ = spearmanr(x, y)
r2 = pearson_r ** 2

fig = px.scatter(
    merged_bm,
    x="log10_baseMean_STAR",
    y="log10_baseMean_Salmon_align",
    opacity=0.4,
    trendline="ols",
    hover_name="transcript_id",
    labels={
        "log10_baseMean_STAR": "STAR - log10(BaseMean + 1)",
        "log10_baseMean_Salmon_align": "Salmon (align) - log10(BaseMean + 1)"
    },
    title="Overall expression agreement: STAR vs. Salmon (align)"
)

fig.add_annotation(
    x=0.05,
    y=0.95,
    xref="paper",
    yref="paper",
    showarrow=False,
    align="left",
    text=(
        f"Pearson r = {pearson_r:.3f}<br>"
        f"Spearman ρ = {spearman_r:.3f}<br>"
        f"R² = {r2:.3f}"
    )
)

fig.update_traces(
    line=dict(color="red", width=1),
    selector=dict(mode="lines")
)

fig.show()

print("STAR vs Salmon (align)")
print(f"  Pearson r  = {pearson_r:.3f}")
print(f"  Spearman ρ = {spearman_r:.3f}")
print(f"  R²         = {r2:.3f}\n")

STAR vs Salmon (align)
  Pearson r  = 0.911
  Spearman ρ = 0.910
  R²         = 0.830

Salmon map vs. STAR + Salmon align

In [32]:
x = merged_bm["log10_baseMean_Salmon_map"]
y = merged_bm["log10_baseMean_Salmon_align"]

pearson_r, _ = pearsonr(x, y)
spearman_r, _ = spearmanr(x, y)
r2 = pearson_r ** 2

fig = px.scatter(
    merged_bm,
    x="log10_baseMean_Salmon_map",
    y="log10_baseMean_Salmon_align",
    opacity=0.4,
    trendline="ols",
    hover_name="transcript_id",
    labels={
        "log10_baseMean_Salmon_map": "Salmon (map) - log10(BaseMean + 1)",
        "log10_baseMean_Salmon_align": "Salmon (align) - log10(BaseMean + 1)"
    },
    title="Overall expression agreement: Salmon map vs. Salmon align"
)

fig.add_annotation(
    x=0.05,
    y=0.95,
    xref="paper",
    yref="paper",
    showarrow=False,
    align="left",
    text=(
        f"Pearson r = {pearson_r:.3f}<br>"
        f"Spearman ρ = {spearman_r:.3f}<br>"
        f"R² = {r2:.3f}"
    )
)

fig.update_traces(
    line=dict(color="red", width=1),
    selector=dict(mode="lines")
)

fig.show()

print("Salmon map vs Salmon align")
print(f"  Pearson r  = {pearson_r:.3f}")
print(f"  Spearman ρ = {spearman_r:.3f}")
print(f"  R²         = {r2:.3f}\n")

Salmon map vs Salmon align
  Pearson r  = 0.986
  Spearman ρ = 0.986
  R²         = 0.971