Software Comparison - Correlation Plots

In [12]:
import numpy as np
import pandas as pd
import plotly.express as px

Load the annotated results

Load Salmon-map DE results

In [13]:
salmon_map_DE = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_map_dominance_DE_sex_results_new_filtering.csv", float_precision='legacy')
# Replace the zeros in padj with 1e-308 avoid log10 issues
salmon_map_DE["padj_safe"] = salmon_map_DE["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
salmon_map_DE["neglog10_padj"] = -np.log10(salmon_map_DE["padj_safe"])


# Add significance to differentially expressed transcripts 
salmon_map_DE["significant"] = (
    (salmon_map_DE["padj"] < 0.05) &
    (salmon_map_DE["log2FoldChange"].abs() > 1)
)

# Add a label to the significant transcripts
salmon_map_DE["label"] = salmon_map_DE["transcript_id"].where(salmon_map_DE["significant"], "")

salmon_map_DE

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,248.420188,0.692250,0.131096,5.280476,1.288487e-07,2.675948e-07,g2.t1,g2,utg000001l,220384.0,...,-,-,ko:K02273,"ko00190,ko01100,ko04260,ko04714,ko04932,ko0501...",I,"2FBM0@1|root,2TCUK@2759|Eukaryota,398E5@33154|...",2.675948e-07,6.572522,False,
1,92.726112,0.655815,0.169749,3.863442,1.118004e-04,1.938610e-04,g3.t1,g3,utg000001l,227675.0,...,"GO:0003674,GO:0005488,GO:0005515,GO:0005543,GO...",3.1.26.5,"ko:K14529,ko:K17543","ko03013,map03013",DUZ,"KOG2101@1|root,KOG2101@2759|Eukaryota,396Y9@33...",1.938610e-04,3.712510,False,
2,136.044931,-0.620454,0.178733,-3.471396,5.177602e-04,8.480073e-04,g4.t1,g4,utg000001l,245866.0,...,"GO:0001101,GO:0001666,GO:0003674,GO:0003824,GO...",2.5.1.61,ko:K01749,"ko00860,ko01100,ko01110,ko01120,map00860,map01...",H,"COG0181@1|root,KOG2892@2759|Eukaryota,38D6W@33...",8.480073e-04,3.071600,False,
3,3.332468,4.516260,0.827360,5.458642,4.797891e-08,1.019443e-07,g5.t1,g5,utg000001l,257697.0,...,"GO:0005575,GO:0005622,GO:0005623,GO:0005737,GO...",-,-,-,I,"KOG2761@1|root,KOG2761@2759|Eukaryota,38F7R@33...",1.019443e-07,6.991637,True,g5.t1
4,381.084979,-0.916813,0.069597,-13.173185,1.252016e-39,7.438447e-39,g6.t1,g6,utg000001l,263441.0,...,-,-,-,-,B,"2E6V3@1|root,2SDHR@2759|Eukaryota",7.438447e-39,38.128518,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17569,20.275098,0.380247,0.209991,1.810783,7.017444e-02,8.988015e-02,g34843.t1,g34843,utg003648l,5656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,8.988015e-02,1.046336,False,
17570,1.364118,2.296660,0.615847,3.729268,1.920367e-04,3.261357e-04,g34884.t1,g34884,utg003700l,19710.0,...,-,-,-,-,S,"2D3G7@1|root,2SRFN@2759|Eukaryota,3AMW9@33154|...",3.261357e-04,3.486602,True,g34884.t1
17571,8.286716,2.238529,0.365104,6.131210,8.721322e-10,2.014570e-09,g34922.t1,g34922,utg003714l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.014570e-09,8.695818,True,g34922.t1
17572,19.121063,2.377057,0.337972,7.033304,2.016994e-12,5.208913e-12,g35167.t1,g35167,utg003885l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.208913e-12,11.283253,True,g35167.t1
17573,3.504696,1.266816,0.531277,2.384472,1.710367e-02,2.392962e-02,g35420.t1,g35420,utg003980l,11626.0,...,-,2.4.2.29,ko:K15407,-,C,"KOG1075@1|root,KOG1075@2759|Eukaryota,39TZY@33...",2.392962e-02,1.621064,True,g35420.t1

Load STAR+featureCounts DE results

In [14]:
star_DE = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/STAR_featureCounts_deseq2_sex_results_fully_annotated_new_filtering.csv", float_precision='legacy')
# Replace the zeros in padj with 1e-308 avoid log10 issues
star_DE["padj_safe"] = star_DE["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
star_DE["neglog10_padj"] = -np.log10(star_DE["padj_safe"])


# Add significance to differentially expressed transcripts 
star_DE["significant"] = (
    (star_DE["padj"] < 0.05) &
    (star_DE["log2FoldChange"].abs() > 1)
)

# Add a label to the significant transcripts
star_DE["label"] = star_DE["transcript_id"].where(star_DE["significant"], "")

star_DE

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,1.153465,-1.241867,0.542189,-2.290471,2.199401e-02,2.983143e-02,g1.t1,g1,utg000001l,185292,...,"GO:0005575,GO:0005622,GO:0005623,GO:0005634,GO...",-,-,-,-,"2DQGE@1|root,2S6BS@2759|Eukaryota,3A6U0@33154|...",2.983143e-02,1.525326,True,g1.t1
1,456.100314,0.539063,0.128924,4.181259,2.898995e-05,5.207459e-05,g10.t1,g10,utg000001l,554496,...,"GO:0003674,GO:0005488,GO:0005509,GO:0043167,GO...",-,-,-,T,"KOG0032@1|root,KOG0032@2759|Eukaryota,38G5X@33...",5.207459e-05,4.283374,False,
2,1836.622862,0.664997,0.074970,8.870166,7.303700e-19,2.400314e-18,g1000.t1,g1000,utg000005l,5092168,...,"GO:0003674,GO:0003824,GO:0004518,GO:0004540,GO...",3.1.27.1,ko:K01166,-,A,"KOG1642@1|root,KOG1642@2759|Eukaryota,38KSQ@33...",2.400314e-18,17.619732,False,
3,9.277403,1.333572,0.214887,6.205932,5.437368e-10,1.266580e-09,g10001.t1,g10001,utg000074l,8915422,...,-,-,-,-,B,"KOG4585@1|root,KOG4585@2759|Eukaryota",1.266580e-09,8.897367,True,g10001.t1
4,5.817209,-0.848882,0.462565,-1.835161,6.648186e-02,8.428873e-02,g10006.t1,g10006,utg000074l,9020033,...,NaN,NaN,NaN,NaN,NaN,NaN,8.428873e-02,1.074231,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17561,20.318618,0.332159,0.149532,2.221320,2.632929e-02,3.535664e-02,g999.t1,g999,utg000005l,4837205,...,"GO:0003674,GO:0003824,GO:0005575,GO:0005622,GO...",-,ko:K17888,"ko04136,ko04138,ko04140,map04136,map04138,map0...",S,"KOG4741@1|root,KOG4741@2759|Eukaryota,39WIU@33...",3.535664e-02,1.451529,False,
17562,5.285936,0.872817,0.339448,2.571282,1.013228e-02,1.435931e-02,g9991.t1,g9991,utg000074l,8820390,...,-,-,-,-,L,"KOG4585@1|root,KOG4585@2759|Eukaryota,3A4U2@33...",1.435931e-02,1.842867,False,
17563,3.573162,1.466915,0.329144,4.456757,8.320878e-06,1.547861e-05,g9992.t1,g9992,utg000074l,8822623,...,NaN,NaN,NaN,NaN,NaN,NaN,1.547861e-05,4.810268,True,g9992.t1
17564,9.375622,0.551459,0.500326,1.102199,2.703753e-01,3.092871e-01,g9993.t1,g9993,utg000074l,8847120,...,-,-,-,-,K,"2E8EB@1|root,2SEWX@2759|Eukaryota,3AC3W@33154|...",3.092871e-01,0.509638,False,
17565,1.915054,1.073576,0.409101,2.624231,8.684490e-03,1.242480e-02,g9997.t1,g9997,utg000074l,8855626,...,-,-,-,-,-,"2BXPG@1|root,2S2FM@2759|Eukaryota,3A3WK@33154|...",1.242480e-02,1.905710,True,g9997.t1

Load Salmon-Align results

In [15]:
salmon_align_DE = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_align_dominance_DE_sex_results_new_filtering.csv", float_precision='legacy')
# Replace the zeros in padj with 1e-308 avoid log10 issues
salmon_align_DE["padj_safe"] = salmon_align_DE["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
salmon_align_DE["neglog10_padj"] = -np.log10(salmon_align_DE["padj_safe"])


# Add significance label to differentially expressed transcripts 
salmon_align_DE["significant"] = (
    (salmon_align_DE["padj"] < 0.05) &
    (salmon_align_DE["log2FoldChange"].abs() > 1)
)

# Add a label to the significant transcripts
salmon_align_DE["label"] = salmon_align_DE["transcript_id"].where(salmon_align_DE["significant"], "")

salmon_align_DE

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,237.825076,0.820721,0.128795,6.372287,1.862300e-10,4.530465e-10,g2.t1,g2,utg000001l,220384.0,...,-,-,ko:K02273,"ko00190,ko01100,ko04260,ko04714,ko04932,ko0501...",I,"2FBM0@1|root,2TCUK@2759|Eukaryota,398E5@33154|...",4.530465e-10,9.343857,False,
1,73.844964,0.663084,0.181367,3.656039,2.561425e-04,4.432381e-04,g3.t1,g3,utg000001l,227675.0,...,"GO:0003674,GO:0005488,GO:0005515,GO:0005543,GO...",3.1.26.5,"ko:K14529,ko:K17543","ko03013,map03013",DUZ,"KOG2101@1|root,KOG2101@2759|Eukaryota,396Y9@33...",4.432381e-04,3.353363,False,
2,115.316375,-0.604007,0.168972,-3.574591,3.507763e-04,6.013374e-04,g4.t1,g4,utg000001l,245866.0,...,"GO:0001101,GO:0001666,GO:0003674,GO:0003824,GO...",2.5.1.61,ko:K01749,"ko00860,ko01100,ko01110,ko01120,map00860,map01...",H,"COG0181@1|root,KOG2892@2759|Eukaryota,38D6W@33...",6.013374e-04,3.220882,False,
3,251.432475,-0.890110,0.062282,-14.291522,2.471491e-46,1.808786e-45,g6.t1,g6,utg000001l,263441.0,...,-,-,-,-,B,"2E6V3@1|root,2SDHR@2759|Eukaryota",1.808786e-45,44.742613,False,
4,42.078202,-0.956817,0.112738,-8.487085,2.118852e-17,6.771986e-17,g7.t1,g7,utg000001l,371755.0,...,"GO:0002682,GO:0002683,GO:0002685,GO:0002686,GO...",-,-,-,Z,"COG4886@1|root,KOG0532@2759|Eukaryota,38HCP@33...",6.771986e-17,16.169284,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16558,11.656909,0.290288,0.220053,1.319173,1.871114e-01,2.293982e-01,g34843.t1,g34843,utg003648l,5656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.293982e-01,0.639410,False,
16559,1.364347,2.303175,0.590766,3.898621,9.674188e-05,1.722282e-04,g34884.t1,g34884,utg003700l,19710.0,...,-,-,-,-,S,"2D3G7@1|root,2SRFN@2759|Eukaryota,3AMW9@33154|...",1.722282e-04,3.763896,True,g34884.t1
16560,2.364626,0.412563,0.360914,1.143107,2.529942e-01,3.014236e-01,g34922.t1,g34922,utg003714l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.014236e-01,0.520823,False,
16561,3.988477,1.153179,0.359851,3.204606,1.352475e-03,2.209006e-03,g35167.t1,g35167,utg003885l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.209006e-03,2.655803,True,g35167.t1
16562,3.287078,1.177383,0.547130,2.151925,3.140326e-02,4.394006e-02,g35420.t1,g35420,utg003980l,11626.0,...,-,2.4.2.29,ko:K15407,-,C,"KOG1075@1|root,KOG1075@2759|Eukaryota,39TZY@33...",4.394006e-02,1.357139,True,g35420.t1

Correlation plots.  
Pairwise comparison of BaseMean per transcript between the softwares
(=mean normalized expression estimates produced by DESeq2)

In [16]:
from scipy.stats import pearsonr, spearmanr
#funtion to extract pearson and spearman R

def report_correlation(x, y, label):
    pearson_r, _ = pearsonr(x, y)
    spearman_r, _ = spearmanr(x, y)
    print(label)
    print(f"  Pearson r  = {pearson_r:.3f}")
    print(f"  Spearman ρ = {spearman_r:.3f}\n")

In [17]:
# function to extract basemean 
def extract_basemean(df, id_col, label):
    bm = df[[id_col, "baseMean"]].copy()
    bm = bm.rename(columns={"baseMean": f"baseMean_{label}"})
    return bm

In [18]:
#extract basemean from all three 
star_bm = extract_basemean(star_DE, "transcript_id", "STAR")
salmon_map_bm = extract_basemean(salmon_map_DE, "transcript_id", "Salmon_map")
salmon_align_bm = extract_basemean(salmon_align_DE, "transcript_id", "Salmon_align")

# merge on transcript_id
merged_bm = (
    star_bm
    .merge(salmon_map_bm, on="transcript_id", how="inner")
    .merge(salmon_align_bm, on="transcript_id", how="inner")
)

print("Number of shared transcripts:", merged_bm.shape[0])
merged_bm.head()

Number of shared transcripts: 14840

  transcript_id  baseMean_STAR  baseMean_Salmon_map  baseMean_Salmon_align
0        g10.t1     456.100314           345.994755             290.822706
1      g1000.t1    1836.622862           734.336268             341.651854
2     g10006.t1       5.817209             2.487832               2.341586
3      g1001.t1      26.227040           180.730637              73.413402
4      g1002.t1     622.382157           611.077939             425.515579

In [19]:
#log10 transformation to handel RNA data

for col in ["baseMean_STAR", "baseMean_Salmon_map", "baseMean_Salmon_align"]:
    merged_bm[f"log10_{col}"] = np.log10(merged_bm[col] + 1)

merged_bm

,transcript_id,baseMean_STAR,baseMean_Salmon_map,baseMean_Salmon_align,log10_baseMean_STAR,log10_baseMean_Salmon_map,log10_baseMean_Salmon_align
0,g10.t1,456.100314,345.994755,290.822706,2.660012,2.540323,2.465119
1,g1000.t1,1836.622862,734.336268,341.651854,3.264256,2.866486,2.534853
2,g10006.t1,5.817209,2.487832,2.341586,0.833607,0.542556,0.523953
3,g1001.t1,26.227040,180.730637,73.413402,1.435000,2.259428,1.871651
4,g1002.t1,622.382157,611.077939,425.515579,2.794754,2.786807,2.629935
...,...,...,...,...,...,...,...
14835,g9973.t1,3.960454,10.464083,9.712877,0.695521,1.059339,1.029906
14836,g998.t1,65.202446,23.874433,22.435232,1.820874,1.395753,1.369869
14837,g999.t1,20.318618,28.892253,13.387113,1.328759,1.475559,1.157974
14838,g9993.t1,9.375622,6.102360,6.674590,1.016014,0.851403,0.885055
14839,g9997.t1,1.915054,7.275085,1.856460,0.464647,0.917772,0.455828

STAR + featureCounts vs Salmon_map

In [20]:
x = merged_bm["log10_baseMean_STAR"]
y = merged_bm["log10_baseMean_Salmon_map"]

pearson_r, _ = pearsonr(x, y)
spearman_r, _ = spearmanr(x, y)
r2 = pearson_r ** 2

fig = px.scatter(
    merged_bm,
    x="log10_baseMean_STAR",
    y="log10_baseMean_Salmon_map",
    opacity=0.4,
    trendline="ols",
    hover_name="transcript_id",
    labels={
        "log10_baseMean_STAR": "STAR - log10(BaseMean + 1)",
        "log10_baseMean_Salmon_map": "Salmon (map) - log10(BaseMean + 1)"
    },
    title="Overall expression agreement: STAR vs. Salmon (map)",
)

fig.add_annotation(
    x=0.05,
    y=0.95,
    xref="paper",
    yref="paper",
    showarrow=False,
    align="left",
    text=(
        f"Pearson r = {pearson_r:.3f}<br>"
        f"Spearman ρ = {spearman_r:.3f}<br>"
        f"R² = {r2:.3f}"
    )
)


fig.update_traces(
    line=dict(color="red", width=1),
    selector=dict(mode="lines")
)

fig.show()

print("STAR vs Salmon (map)")
print(f"  Pearson r  = {pearson_r:.3f}")
print(f"  Spearman ρ = {spearman_r:.3f}")
print(f"  R²         = {r2:.3f}\n")

STAR vs Salmon (map)
  Pearson r  = 0.927
  Spearman ρ = 0.928
  R²         = 0.859

STAR + featureCounts vs. STAR + Salmon_align

In [21]:
x = merged_bm["log10_baseMean_STAR"]
y = merged_bm["log10_baseMean_Salmon_align"]

pearson_r, _ = pearsonr(x, y)
spearman_r, _ = spearmanr(x, y)
r2 = pearson_r ** 2

fig = px.scatter(
    merged_bm,
    x="log10_baseMean_STAR",
    y="log10_baseMean_Salmon_align",
    opacity=0.4,
    trendline="ols",
    hover_name="transcript_id",
    labels={
        "log10_baseMean_STAR": "STAR - log10(BaseMean + 1)",
        "log10_baseMean_Salmon_align": "Salmon (align) - log10(BaseMean + 1)"
    },
    title="Overall expression agreement: STAR vs. Salmon (align)"
)

fig.add_annotation(
    x=0.05,
    y=0.95,
    xref="paper",
    yref="paper",
    showarrow=False,
    align="left",
    text=(
        f"Pearson r = {pearson_r:.3f}<br>"
        f"Spearman ρ = {spearman_r:.3f}<br>"
        f"R² = {r2:.3f}"
    )
)

fig.update_traces(
    line=dict(color="red", width=1),
    selector=dict(mode="lines")
)

fig.show()

print("STAR vs Salmon (align)")
print(f"  Pearson r  = {pearson_r:.3f}")
print(f"  Spearman ρ = {spearman_r:.3f}")
print(f"  R²         = {r2:.3f}\n")

STAR vs Salmon (align)
  Pearson r  = 0.923
  Spearman ρ = 0.924
  R²         = 0.851

Salmon map vs. STAR + Salmon align

In [22]:
x = merged_bm["log10_baseMean_Salmon_map"]
y = merged_bm["log10_baseMean_Salmon_align"]

pearson_r, _ = pearsonr(x, y)
spearman_r, _ = spearmanr(x, y)
r2 = pearson_r ** 2

fig = px.scatter(
    merged_bm,
    x="log10_baseMean_Salmon_map",
    y="log10_baseMean_Salmon_align",
    opacity=0.4,
    trendline="ols",
    hover_name="transcript_id",
    labels={
        "log10_baseMean_Salmon_map": "Salmon (map) - log10(BaseMean + 1)",
        "log10_baseMean_Salmon_align": "Salmon (align) - log10(BaseMean + 1)"
    },
    title="Overall expression agreement: Salmon map vs. Salmon align"
)

fig.add_annotation(
    x=0.05,
    y=0.95,
    xref="paper",
    yref="paper",
    showarrow=False,
    align="left",
    text=(
        f"Pearson r = {pearson_r:.3f}<br>"
        f"Spearman ρ = {spearman_r:.3f}<br>"
        f"R² = {r2:.3f}"
    )
)

fig.update_traces(
    line=dict(color="red", width=1),
    selector=dict(mode="lines")
)

fig.show()

print("Salmon map vs Salmon align")
print(f"  Pearson r  = {pearson_r:.3f}")
print(f"  Spearman ρ = {spearman_r:.3f}")
print(f"  R²         = {r2:.3f}\n")

Salmon map vs Salmon align
  Pearson r  = 0.987
  Spearman ρ = 0.987
  R²         = 0.974