For the unfiltered, consistent annotations, using the whole genome decoys.

Load packages

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

from sklearn.decomposition import PCA

PCA

Load the datasets created in R

In [2]:
norm_counts = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_mapping_normalized_counts_transcript_consistent_new_filtering.csv", index_col=0)
norm_counts

,ERR12356072,ERR12383247,ERR12383248,ERR12383249,ERR12383250,ERR12383251,ERR12383252,ERR12383253,ERR12383254,ERR12383255,...,ERR12383308,ERR12383309,ERR12383310,ERR12383311,ERR12383312,ERR12383313,ERR12383314,ERR12383315,ERR12383316,ERR12383317
g2.t1,7.890337,8.066325,8.207593,8.993410,8.489254,9.210914,7.798844,8.055555,8.122869,8.783708,...,8.472937,8.162432,8.400815,7.720509,7.854738,8.343819,7.819224,8.172276,8.250370,9.007101
g3.t1,7.118099,6.994008,7.515935,7.218227,7.870856,7.627084,6.830453,7.504254,7.181763,7.425527,...,6.705230,7.044201,6.580121,5.976352,6.318528,6.422607,6.494674,7.686265,7.851981,7.482269
g4.t1,7.544627,7.552430,7.504665,7.015594,7.048879,7.012562,7.478367,7.355220,7.633907,7.004220,...,7.300862,7.327468,7.329026,7.513124,7.537132,7.394785,7.415408,6.999393,7.070820,6.443215
g5.t1,4.747688,5.114768,4.747688,5.603178,5.365333,5.432020,4.931023,4.747688,5.389269,6.077018,...,4.747688,4.747688,4.747688,5.037690,4.747688,4.920461,4.747688,5.924924,5.475382,4.747688
g6.t1,8.602570,9.007825,8.410272,8.026586,8.366266,8.224853,8.960625,8.657728,8.864994,8.419417,...,8.225711,8.238262,8.503436,8.773836,9.005747,9.029822,8.972232,8.294467,8.005957,7.904037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
g34843.t1,5.598861,6.004241,6.131843,6.163016,5.731835,6.401755,5.843280,5.623514,5.795467,6.232995,...,5.418095,4.973372,5.248152,5.902201,5.157222,5.167073,5.622059,6.445340,5.999450,6.043126
g34884.t1,4.747688,4.985489,4.747688,4.747688,4.747688,5.366688,4.984004,4.747688,4.747688,4.747688,...,5.700012,5.426219,4.990370,5.006404,4.926208,5.235754,4.747688,5.275996,5.021114,5.349274
g34922.t1,5.334370,5.309371,5.294022,5.382637,5.322007,5.822029,5.377698,5.079428,5.365281,4.747688,...,6.615556,5.650851,5.412536,5.407994,5.120284,5.331308,5.354016,5.998628,4.747688,5.292844
g35167.t1,5.368999,5.431595,5.996252,6.064505,5.560033,6.093863,5.633848,5.723479,6.286107,5.269084,...,7.452641,5.630609,5.525375,5.613050,5.520684,5.318427,5.171690,7.480299,6.214580,6.626048
g35420.t1,4.960547,4.990318,4.747688,4.747688,4.747688,4.747688,4.998984,4.747688,4.747688,5.309098,...,5.385432,5.085640,5.009713,4.747688,4.747688,4.747688,5.099557,5.311488,5.164420,4.747688

In [3]:
#Metadata
metadata = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/dominance_meta_corrected_outlier_corrected.csv")

#make sure order matches norm_counts
metadata = metadata.set_index('Run')
metadata = metadata.reindex(norm_counts.columns)
# Now Run is the index, and metadata is aligned with counts
print("Metadata index (samples):", metadata.index[:5].tolist())
print("Counts columns:", norm_counts.columns[:5].tolist())
print("Match?", all(metadata.index == norm_counts.columns))
metadata

Metadata index (samples): ['ERR12356072', 'ERR12383247', 'ERR12383248', 'ERR12383249', 'ERR12383250']
Counts columns: ['ERR12356072', 'ERR12383247', 'ERR12383248', 'ERR12383249', 'ERR12383250']
Match? True

,Bases,BioProject,BioSample,Experiment,sample_name,TF ID,Sample ID,Cross,Family,Sex,original_fastq_name_R1,original_fastq_name_R2,Notes
ERR12356072,21027960416,PRJEB70958,SAMEA114860228,ERX11733017,Sample 1 males genotype BA heterozygote,TF2581-10-e3,10e 3,13:20 (M) + 42:13 (F),"2,3,4,",F,TF-2581-10-e3_S67_L001_R1_001.fastq.gz,TF-2581-10-e3_S67_L001_R2_001.fastq.gz,NaN
ERR12383247,14794943760,PRJEB70958,SAMEA114860213,ERX11759665,Sample 1 females genotype AA homozygote,TF2581-11,11,13:20 (M) + 42:13 (F),"2,3,4,",F,TF-2581-11_S9_L001_R1_001.fastq.gz,TF-2581-11_S9_L001_R2_001.fastq.gz,NaN
ERR12383248,15610248328,PRJEB70958,SAMEA114860214,ERX11759666,Sample 2 females genotype AA homozygote,TF2581-12,12,13:20 (M) + 42:13 (F),"2,3,4,",F,TF-2581-12_S10_L001_R1_001.fastq.gz,TF-2581-12_S10_L001_R2_001.fastq.gz,NaN
ERR12383249,9412089720,PRJEB70958,SAMEA114860215,ERX11759667,Sample 3 females genotype AA homozygote,TF2581-13,13,42:13 (M) + 13:20 (F),"1,4,8",M,TF-2581-13_S11_L001_R1_001.fastq.gz,TF-2581-13_S11_L001_R2_001.fastq.gz,NaN
ERR12383250,9959631122,PRJEB70958,SAMEA114860216,ERX11759668,Sample 1 males genotype AA homozygote,TF2581-14-e2,14e 2,42:13 (M) + 13:20 (F),"1,4,8",M,TF-2581-14-e2_S68_L001_R1_001.fastq.gz,TF-2581-14-e2_S68_L001_R2_001.fastq.gz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
ERR12383313,27406244206,PRJEB70958,SAMEA114860279,ERX11759731,Sample 1 females genotype FF homozygote,TF2581-71,71,4:18 + 4:18,"2,6,9",F,TF-2581-71_S59_L001_R1_001.fastq.gz,TF-2581-71_S59_L001_R2_001.fastq.gz,"Had TF ID: TF2581-70, and Sample ID: 71"
ERR12383314,13458064958,PRJEB70958,SAMEA114860280,ERX11759732,Sample 2 females genotype FF homozygote,TF2581-72,72,4:18 + 4:18,"2,6,9",F,TF-2581-72_S60_L001_R1_001.fastq.gz,TF-2581-72_S60_L001_R2_001.fastq.gz,"Had TF ID: TF2581-71, and Sample ID: 72"
ERR12383315,11890141660,PRJEB70958,SAMEA114860281,ERX11759733,Sample 3 females genotype FF homozygote,TF2581-7,7,13:20 (M) + 42:13 (F),"2,3,4,",M,TF-2581-7_S7_L001_R1_001.fastq.gz,TF-2581-7_S7_L001_R2_001.fastq.gz,NaN
ERR12383316,13692674262,PRJEB70958,SAMEA114860282,ERX11759734,Sample 1 males genotype FF homozygote,TF2581-8,8,13:20 (M) + 42:13 (F),"2,3,4,",M,TF-2581-8_S8_L001_R1_001.fastq.gz,TF-2581-8_S8_L001_R2_001.fastq.gz,NaN
ERR12383317,14658478416,PRJEB70958,SAMEA114860283,ERX11759735,Sample 2 males genotype FF homozygote,TF2581-9e,9e,13:20 (M) + 42:13 (F),"2,3,4,",M,TF-2581-9e_S61_L001_R1_001.fastq.gz,TF-2581-9e_S61_L001_R2_001.fastq.gz,NaN

In [4]:
# create transpose
vst_t = norm_counts.T

pca = PCA(n_components=2)
pca_scores = pca.fit_transform(vst_t)

pca_df = metadata.copy()
pca_df['PC1'] = pca_scores[:,0]
pca_df['PC2'] = pca_scores[:,1]

# Explained variance
pc1_var = pca.explained_variance_ratio_[0] * 100
pc2_var = pca.explained_variance_ratio_[1] * 100

# Define your own color mapping
color_map = {'M': 'blue', 'F': 'red'}  

fig = px.scatter(
    pca_df,
    x='PC1',
    y='PC2',
    color='Sex',  
    color_discrete_map=color_map,          
    hover_name=pca_df.index,
    title=f"Salmon-Map: Male vs. Female PCA of VST-normalized counts"
)

fig.update_layout(
    xaxis_title=f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% var)",
    yaxis_title=f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% var)",
)
fig.show()

Volcano Plot

In [5]:
results_full_annot = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_map_dominance_DE_sex_results_new_filtering.csv", float_precision='legacy')
results_full_annot

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,HOG,OG,Gene.Tree.Parent.Clade,PFAMs,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs
0,248.420188,0.692250,0.131096,5.280476,1.288487e-07,2.675948e-07,g2.t1,g2,utg000001l,220384.0,...,N0.HOG0012111,OG0011460,n0,COX8,-,-,ko:K02273,"ko00190,ko01100,ko04260,ko04714,ko04932,ko0501...",I,"2FBM0@1|root,2TCUK@2759|Eukaryota,398E5@33154|..."
1,92.726112,0.655815,0.169749,3.863442,1.118004e-04,1.938610e-04,g3.t1,g3,utg000001l,227675.0,...,N0.HOG0004052,OG0003481,n0,"PX,Pkinase,Pkinase_Tyr,WH2","GO:0003674,GO:0005488,GO:0005515,GO:0005543,GO...",3.1.26.5,"ko:K14529,ko:K17543","ko03013,map03013",DUZ,"KOG2101@1|root,KOG2101@2759|Eukaryota,396Y9@33..."
2,136.044931,-0.620454,0.178733,-3.471396,5.177602e-04,8.480073e-04,g4.t1,g4,utg000001l,245866.0,...,N0.HOG0004826,OG0004221,n0,"Porphobil_deam,Porphobil_deamC","GO:0001101,GO:0001666,GO:0003674,GO:0003824,GO...",2.5.1.61,ko:K01749,"ko00860,ko01100,ko01110,ko01120,map00860,map01...",H,"COG0181@1|root,KOG2892@2759|Eukaryota,38D6W@33..."
3,3.332468,4.516260,0.827360,5.458642,4.797891e-08,1.019443e-07,g5.t1,g5,utg000001l,257697.0,...,N0.HOG0006068,OG0005448,n0,START,"GO:0005575,GO:0005622,GO:0005623,GO:0005737,GO...",-,-,-,I,"KOG2761@1|root,KOG2761@2759|Eukaryota,38F7R@33..."
4,381.084979,-0.916813,0.069597,-13.173185,1.252016e-39,7.438447e-39,g6.t1,g6,utg000001l,263441.0,...,N0.HOG0015574,OG0014921,n0,THAP,-,-,-,-,B,"2E6V3@1|root,2SDHR@2759|Eukaryota"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17569,20.275098,0.380247,0.209991,1.810783,7.017444e-02,8.988015e-02,g34843.t1,g34843,utg003648l,5656.0,...,N0.HOG0012740,OG0012089,n0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17570,1.364118,2.296660,0.615847,3.729268,1.920367e-04,3.261357e-04,g34884.t1,g34884,utg003700l,19710.0,...,N0.HOG0000536,OG0000347,n0,Retrotrans_gag,-,-,-,-,S,"2D3G7@1|root,2SRFN@2759|Eukaryota,3AMW9@33154|..."
17571,8.286716,2.238529,0.365104,6.131210,8.721322e-10,2.014570e-09,g34922.t1,g34922,utg003714l,1.0,...,N0.HOG0000406,OG0000247,n0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17572,19.121063,2.377057,0.337972,7.033304,2.016994e-12,5.208913e-12,g35167.t1,g35167,utg003885l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17573,3.504696,1.266816,0.531277,2.384472,1.710367e-02,2.392962e-02,g35420.t1,g35420,utg003980l,11626.0,...,N0.HOG0000672,OG0000459,n0,"Exo_endo_phos_2,RVT_1",-,2.4.2.29,ko:K15407,-,C,"KOG1075@1|root,KOG1075@2759|Eukaryota,39TZY@33..."

In [6]:
# Replace the zeros in padj with 1e-308 avoid log10 issues
results_full_annot["padj_safe"] = results_full_annot["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
results_full_annot["neglog10_padj"] = -np.log10(results_full_annot["padj_safe"])


# Add significance to differentially expressed genes 
results_full_annot["significant"] = (
    (results_full_annot["padj"] < 0.05) &
    (results_full_annot["log2FoldChange"].abs() > 1)
)

# Add a label to the significant genes
results_full_annot["label"] = results_full_annot["gene_id"].where(results_full_annot["significant"], "")

results_full_annot

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
0,248.420188,0.692250,0.131096,5.280476,1.288487e-07,2.675948e-07,g2.t1,g2,utg000001l,220384.0,...,-,-,ko:K02273,"ko00190,ko01100,ko04260,ko04714,ko04932,ko0501...",I,"2FBM0@1|root,2TCUK@2759|Eukaryota,398E5@33154|...",2.675948e-07,6.572522,False,
1,92.726112,0.655815,0.169749,3.863442,1.118004e-04,1.938610e-04,g3.t1,g3,utg000001l,227675.0,...,"GO:0003674,GO:0005488,GO:0005515,GO:0005543,GO...",3.1.26.5,"ko:K14529,ko:K17543","ko03013,map03013",DUZ,"KOG2101@1|root,KOG2101@2759|Eukaryota,396Y9@33...",1.938610e-04,3.712510,False,
2,136.044931,-0.620454,0.178733,-3.471396,5.177602e-04,8.480073e-04,g4.t1,g4,utg000001l,245866.0,...,"GO:0001101,GO:0001666,GO:0003674,GO:0003824,GO...",2.5.1.61,ko:K01749,"ko00860,ko01100,ko01110,ko01120,map00860,map01...",H,"COG0181@1|root,KOG2892@2759|Eukaryota,38D6W@33...",8.480073e-04,3.071600,False,
3,3.332468,4.516260,0.827360,5.458642,4.797891e-08,1.019443e-07,g5.t1,g5,utg000001l,257697.0,...,"GO:0005575,GO:0005622,GO:0005623,GO:0005737,GO...",-,-,-,I,"KOG2761@1|root,KOG2761@2759|Eukaryota,38F7R@33...",1.019443e-07,6.991637,True,g5
4,381.084979,-0.916813,0.069597,-13.173185,1.252016e-39,7.438447e-39,g6.t1,g6,utg000001l,263441.0,...,-,-,-,-,B,"2E6V3@1|root,2SDHR@2759|Eukaryota",7.438447e-39,38.128518,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17569,20.275098,0.380247,0.209991,1.810783,7.017444e-02,8.988015e-02,g34843.t1,g34843,utg003648l,5656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,8.988015e-02,1.046336,False,
17570,1.364118,2.296660,0.615847,3.729268,1.920367e-04,3.261357e-04,g34884.t1,g34884,utg003700l,19710.0,...,-,-,-,-,S,"2D3G7@1|root,2SRFN@2759|Eukaryota,3AMW9@33154|...",3.261357e-04,3.486602,True,g34884
17571,8.286716,2.238529,0.365104,6.131210,8.721322e-10,2.014570e-09,g34922.t1,g34922,utg003714l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.014570e-09,8.695818,True,g34922
17572,19.121063,2.377057,0.337972,7.033304,2.016994e-12,5.208913e-12,g35167.t1,g35167,utg003885l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.208913e-12,11.283253,True,g35167
17573,3.504696,1.266816,0.531277,2.384472,1.710367e-02,2.392962e-02,g35420.t1,g35420,utg003980l,11626.0,...,-,2.4.2.29,ko:K15407,-,C,"KOG1075@1|root,KOG1075@2759|Eukaryota,39TZY@33...",2.392962e-02,1.621064,True,g35420

In [7]:
fig = px.scatter(
    results_full_annot,
    x="log2FoldChange",
    y="neglog10_padj",
    hover_name="transcript_id",
    hover_data=["padj", "HOG", "PFAMs"],  # Use the columns that already exist
    color="significant",
    color_discrete_map={True: "red", False: "blue"},
    title="Salmon-Map: Volcano Plot (Male vs. Female Transcript Expression)"
)

fig.update_traces(textposition='top center', textfont_size=8)

fig.update_layout(
    xaxis_title="log2 Fold Change (male vs female)",
    yaxis_title="-log10(padj (FDR))",
)

# Horizontal FDR=0.05 cutoff
padj_cut = -np.log10(0.05)

fig.add_hline(
    y=padj_cut,
    line_dash="dash",
    line_color="grey",
    annotation_text="padj = 0.05",
    annotation_position="bottom right"
)

# Vertical log2FC cutoffs
fig.add_vline(
    x=-1,
    line_dash="dash",
    line_color="grey",
    annotation_text="log2FC = -1",
    annotation_position="top left"
)
fig.add_vline(
    x=1,
    line_dash="dash",
    line_color="grey",
    annotation_text="log2FC = 1",
    annotation_position="top right"
)

fig.show()


#DE genes
sig_counts = results_full_annot["significant"].sum()
higher_in_m = ((results_full_annot["significant"]) & 
               (results_full_annot["log2FoldChange"] > 0)).sum()
higher_in_f = ((results_full_annot["significant"]) & 
               (results_full_annot["log2FoldChange"] < 0)).sum()

print(f"Total significant transcripts: {sig_counts}")
print(f"Higher in males: {higher_in_m}")
print(f"Higher in females: {higher_in_f}")

Total significant transcripts: 7134
Higher in males: 4931
Higher in females: 2203

Significant Transcripts

In [8]:
sig_transcripts = results_full_annot[results_full_annot["significant"]]

sig_transcripts

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,start,...,GOs,EC,KEGG_ko,KEGG_Pathway,COG_category,eggNOG_OGs,padj_safe,neglog10_padj,significant,label
3,3.332468,4.516260,0.827360,5.458642,4.797891e-08,1.019443e-07,g5.t1,g5,utg000001l,257697.0,...,"GO:0005575,GO:0005622,GO:0005623,GO:0005737,GO...",-,-,-,I,"KOG2761@1|root,KOG2761@2759|Eukaryota,38F7R@33...",1.019443e-07,6.991637,True,g5
5,70.718212,-1.042897,0.092720,-11.247838,2.373373e-29,1.072779e-28,g7.t1,g7,utg000001l,371755.0,...,"GO:0002682,GO:0002683,GO:0002685,GO:0002686,GO...",-,-,-,Z,"COG4886@1|root,KOG0532@2759|Eukaryota,38HCP@33...",1.072779e-28,27.969490,True,g7
6,475.721002,1.108108,0.072367,15.312386,6.320193e-53,5.190237e-52,g8.t1,g8,utg000001l,510966.0,...,"GO:0005575,GO:0005623,GO:0005886,GO:0005887,GO...",-,"ko:K17352,ko:K17353",-,S,"KOG3882@1|root,KOG3882@2759|Eukaryota,39VAJ@33...",5.190237e-52,51.284813,True,g8
7,97.175715,1.440532,0.178910,8.051692,8.165737e-16,2.401752e-15,g9.t1,g9,utg000001l,531498.0,...,"GO:0003674,GO:0005488,GO:0005509,GO:0043167,GO...",-,-,-,T,"KOG0032@1|root,KOG0032@2759|Eukaryota,38G5X@33...",2.401752e-15,14.619472,True,g9
11,237.620281,-3.903656,0.197214,-19.794020,3.352084e-87,5.605093e-86,g13.t1,g13,utg000001l,666271.0,...,"GO:0000003,GO:0000022,GO:0000070,GO:0000226,GO...",-,ko:K16733,-,T,"KOG3564@1|root,KOG3564@2759|Eukaryota,38ECX@33...",5.605093e-86,85.251417,True,g13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17566,1.283803,2.473537,0.754159,3.279862,1.038581e-03,1.654611e-03,g34618.t1,g34618,utg003533l,36167.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.654611e-03,2.781304,True,g34618
17570,1.364118,2.296660,0.615847,3.729268,1.920367e-04,3.261357e-04,g34884.t1,g34884,utg003700l,19710.0,...,-,-,-,-,S,"2D3G7@1|root,2SRFN@2759|Eukaryota,3AMW9@33154|...",3.261357e-04,3.486602,True,g34884
17571,8.286716,2.238529,0.365104,6.131210,8.721322e-10,2.014570e-09,g34922.t1,g34922,utg003714l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.014570e-09,8.695818,True,g34922
17572,19.121063,2.377057,0.337972,7.033304,2.016994e-12,5.208913e-12,g35167.t1,g35167,utg003885l,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.208913e-12,11.283253,True,g35167
17573,3.504696,1.266816,0.531277,2.384472,1.710367e-02,2.392962e-02,g35420.t1,g35420,utg003980l,11626.0,...,-,2.4.2.29,ko:K15407,-,C,"KOG1075@1|root,KOG1075@2759|Eukaryota,39TZY@33...",2.392962e-02,1.621064,True,g35420